apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: test-table
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  forProvider:
    region: us-west-2
    attributeDefinitions:
      - attributeName: css
        attributeType: S
    billingMode: PAY_PER_REQUEST
    keySchema:
      - attributeName: css
        keyType: HASH
  providerConfigRef:
    name: provider-aws-config
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-aws-config
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.36.1
  controllerConfigRef:
    name: aws-config